### ISSUE TITLE
Issue on Thruk Mobile after upgrading to 1.30

### ISSUE THREAD

**Issue by daividh** [sni/Thruk#73]
Hi,

After upgrading to Thruk 1.30, mobile version stop working (white screen when calling mobile.cgi)
It's seems to be linked to the jquery update embedded wiht the new 1.30.

In my javascript console I have this stacktrace :

url.match is not a function @........./thruk/plugins/mobile/jquery.mobile.router-0.6.js:216

Can you reproduce the problem ?
