### ISSUE TITLE
Thruk doesn`t start after Update to 1.64-2

### ISSUE THREAD

**Issue by joerg16** [sni/Thruk#139]
[Mon Feb 25 12:43:28 2013] [notice] mod_fcgid: process /usr/share/thruk/fcgid_env.sh(22974) exit(shutting down), get stop signal 9
[Mon Feb 25 12:43:28 2013] [notice] Apache/2.2.12 (Linux/SUSE) PHP/5.2.14 with Suhosin-Patch mod_ssl/2.2.12 OpenSSL/0.9.8j-fips configured -- resuming normal operations
Can't locate Moose.pm in @INC (@INC contains: /usr/share/thruk/lib /usr/lib/thruk/perl5 /usr/lib/perl5/5.10.0/x86_64-linux-thread-multi /usr/lib/perl5/5.10.0 /usr/lib/perl5/site_perl/5.10.0/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.10.0 /usr/lib/perl5/vendor_perl
/5.10.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.10.0 /usr/lib/perl5/vendor_perl .) at /usr/lib/thruk/perl5/Catalyst/ScriptRunner.pm line 2.
BEGIN failed--compilation aborted at /usr/lib/thruk/perl5/Catalyst/ScriptRunner.pm line 2.
Compilation failed in require at /usr/share/thruk/script/thruk_fastcgi.pl line 9.
BEGIN failed--compilation aborted at /usr/share/thruk/script/thruk_fastcgi.pl line 9.

With Version 1.64-1 all works fine.
