### ISSUE TITLE
Thruk unable to update logcache

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1107]
Since upgrading to 2.42.2 (ConSol Labs) we are getting the following Errors when we try to update the logcache:
```
# sudo -u apache /usr/bin/thruk logcache update
[ERROR] Can't locate Thread/Queue.pm in @INC (@INC contains: /etc/thruk/plugins//plugins-enabled/statusmap/lib /etc/thruk/plugins//plugins-enabled/reports2/lib /etc/thruk/plugins//plugins-enabled/panorama/lib /etc/thruk/plugins//plugins-enabled/mobile/lib /etc/thruk/plugins//plugins-enabled/minemap/lib /etc/thruk/plugins//plugins-enabled/core_scheduling/lib /etc/thruk/plugins//plugins-enabled/conf/lib /etc/thruk/plugins//plugins-enabled/business_process/lib /usr/share/thruk/lib /usr/lib64/thruk/perl5/x86_64-linux-thread-multi /usr/lib64/thruk/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/thruk/lib/Thruk/Pool/Simple.pm line 6.
[ERROR] BEGIN failed--compilation aborted at /usr/share/thruk/lib/Thruk/Pool/Simple.pm line 6.
[ERROR] Compilation failed in require at /usr/share/thruk/lib/Thruk/Utils/CLI/Logcache.pm line 55.
[ERROR] BEGIN failed--compilation aborted at /usr/share/thruk/lib/Thruk/Utils/CLI/Logcache.pm line 55.
[ERROR] Compilation failed in require at /usr/lib64/thruk/perl5/Module/Load.pm line 77.
[ERROR] Can't locate Thruk/Utils/CLI/Logcache in @INC (@INC contains: /etc/thruk/plugins//plugins-enabled/statusmap/lib /etc/thruk/plugins//plugins-enabled/reports2/lib /etc/thruk/plugins//plugins-enabled/panorama/lib /etc/thruk/plugins//plugins-enabled/mobile/lib /etc/thruk/plugins//plugins-enabled/minemap/lib /etc/thruk/plugins//plugins-enabled/core_scheduling/lib /etc/thruk/plugins//plugins-enabled/conf/lib /etc/thruk/plugins//plugins-enabled/business_process/lib /usr/share/thruk/lib /usr/lib64/thruk/perl5/x86_64-linux-thread-multi /usr/lib64/thruk/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib64/thruk/perl5/Module/Load.pm line 77.
FAILED - to load command module: logcache.
```

I think this could also be the "core issue" for #1103

**Comment by dan-m-joh** [comment]
It looks like the RPMs at ConSol Labs are missing a dependency for `perl-Thread-Queue`.

After "manually" installing `perl-Thread-Queue` the `thruk logcache update` runs without errors.
#1103 is also "solved" and shows correct values.

Now I just have to implement a nagios check that the logcache gets updated...

You can close this issue (and #1103) at your leisure.

Regards,
Dan

**Comment by sni** [comment]
thanks, they were indeed missing, i just added them https://github.com/sni/thruk_libs/commit/c2f9b35d03c80067c1072292dcedb922eab186c7
